### ISSUE TITLE
Failed to lookup symbol 'sodium_init'

### ISSUE THREAD

**Issue by TalebRafiepour** [Tezsure/Dartez#3]
The error log: 

```
flutter: error: Invalid argument(s): Failed to lookup symbol 'sodium_init': dlsym(RTLD_DEFAULT, sodium_init): symbol not found, stack: #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      new SodiumBindings (package:flutter_sodium/src/bindings/sodium_bindings.dart:9:8)
#2      Sodium._sodium (package:flutter_sodium/src/sodium.dart:51:26)
#3      Sodium._sodium (package:flutter_sodium/src/sodium.dart)
#4      Sodium.init (package:flutter_sodium/src/sodium.dart:1943:9)
#5      SodiumUtilsImpl.init (package:dartez/utils/sodium/platform_impl/sodium_utils_io.dart:9:26)
#6      SodiumUtils.init (package:dartez/utils/sodium/sodium_utils.dart:13:32)
#7      Dartez.init (package:dartez/src/dartez.dart:34:23)
```

flutter doctor --verbose: 

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.2 21D49 darwin-arm (Rosetta), locale en-US)
    • Flutter version 3.0.3 at /Users/taleb/fvm/versions/3.0.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (8 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/taleb/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/taleb/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/taleb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 31251278-306E-4021-808D-FB591BCE53D7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.2 21D49 darwin-arm (Rosetta)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by Jay-Tezsure** [comment]
@TalebRafiepour Try adding this line into your podfile of ios project and set deployment target to 13.0
`config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"`
`config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'`

![Screenshot 2022-08-21 at 2 45 52 AM](https://user-images.githubusercontent.com/76425320/185766233-30713775-5cf2-4af2-b658-fcc7e33840b6.png)

Then delete the Podfile.lock and run all this command to clear the cache and reinit the pods in your project directory
```
flutter clean
cd ios
pod deintegrate
pod install
cd ..
flutter pub cache repair
flutter pub get
flutter run
```

If this solution don't work then please share the device specs and the portion of the code you are trying to run.

**Comment by TalebRafiepour** [comment]
@Jay-Tezsure  Thank you so much. It fixed my problem.

**Comment by Imdavyking** [comment]
ios simulator
